name: pdataframe
description: A DataFrame implementation in Dart for data manipulation and analysis.
repository: https://github.com/hyraxcore/pdataframe
version: 0.1.0

environment:
  sdk: ^3.4.4

dependencies:
  csv: ^6.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  matcher: any